import Layout from "../src/components/Layout";
import localFont from "next/font/local";
import "./globals.css";

const vazirFont = localFont({
  src: "../public/font/Vazirmatn-Regular.woff2",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-900 text-slate-200 ${vazirFont.className}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
